kerochuu/20200614/README.md
kerochuu/20200614/음주코딩_펜윅.java
kerochuu/20200614/적록색약.java

[결재] 2주차 학습과제 pull request 件

---

kerochuu/20200621/README.md
kerochuu/20200621/수열과쿼리21.java
kerochuu/20200621/좋은수열.java
kerochuu/20200621/지뢰제거.java

Reverts Road-of-CODEr/stupid-week#4

20200621 kerochuu

---

.github/ISSUE_TEMPLATE.md

chore(ISSUE_TEMPLATE): remove default template

---

minhyungPark/20200920/README.md

1. one percent network
2. 리눅스 운영 체제의 이해와 개발
3. k8s 강의 듣기

chore: add objective 20th Sep

---

2020/09/week3/1ilsang/README.md
2020/09/week3/1ilsang/algorithm/README.md
2020/09/week3/1ilsang/algorithm/boj9498.js
2020/09/week3/1ilsang/algorithm/leetcode1576.js
2020/09/week3/1ilsang/algorithm/leetcode1577.js
2020/09/week3/1ilsang/english.md
2020/09/week4/1ilsang/README.md

1. Leetcode + 백준
2. 네이버 오늘의 영어회화 + 왕초보 100일
3. 배민 React&TS 테크러닝 후기 쓰기

feat: 3주차 완료

---

2020/10/week1/jjeda/README.md

feat: Complete 1th week of Oct

---

2020/10/week1/huisam/README.md
2020/10/week2/huisam/README.md

1. Spring `Log4j2` 를 포스팅 하는 방법
2. Spring `DI` 프로젝트 문서화
3. Clean Code 정리하기

feat: huisam 10월 1주차 완료

---

2020/10/week1/juheekimm/README.md

1. 백준 알고리즘 문제풀이1 - 2733.Brainf*ck
2. 백준 알고리즘 문제풀이2 - 16768.Mooyo Mooyo
3. 백준 알고리즘 문제풀이3 - 1966.프린터 큐

complete 1st week of Oct.

---

.github/PULL_REQUEST_TEMPLATE.md

chore: PR_template

---

2020/10/week1/kerochuu/README.md

README.md 내용 中 사진 확장자 명 변경으로 인한 결재 올립니다.
확인 후 재가 부탁드립니다.

Refactor: Change README.md

---

2020/10/week2/kerochuu/N으로만들기.java
2020/10/week2/kerochuu/README.md
2020/10/week2/kerochuu/저울.java
2020/10/week2/kerochuu/트리의색깔과쿼리.java

1. offline-query를 사용한 union-find 심화문제 풀이
2. floyd-warshall 문제 풀이
3. recursive한 simulation 문제 풀이
1. 구름 알고리즘 문제 출제
2. 알고리즘 문제 풀이
3. 코테 응시

feat: Complete 2nd week of Oct

---

2020/10/week3/huisam/README.md
2020/10/week4/huisam/README.md

1. Line 면접
2. [Spring DI 블로그 포스팅](https://huisam.tistory.com/entry/springDI)
3. HTTP 완벽 가이드 17장 정리
1. 기술 세미나 자료 정리
2. Interview Java 파트 정리
3. HTTP 완벽 가이드 20장 정리

huisam: 10월 3주차 완료

---

2020/10/week3/jjeda/README.md

1. 1% 네트워크 1장 읽기
2. 1% 네트워크 2장 읽기
3. 1% 네트워크 3장 읽기
1. 1% 네트워크 4장 읽기
2. 1% 네트워크 5장 읽기
3. 1% 네트워크 6장 읽기

feat: Complete 3rd week of Oct

---

2020/10/week3/minhyungPark/README.md
2020/10/week3/minhyungPark/algorithm/Leetcode1614.kt
2020/10/week3/minhyungPark/algorithm/Leetcode1615.kt
2020/10/week3/minhyungPark/algorithm/Leetcode1616.kt

1. Algorithm
2. Algorithm
3. Algorithm
1. Algorithm
2. Algorithm
3. Algorithm

10월 3주차 완료

---

2020/10/week3/1ilsang/README.md
2020/10/week3/1ilsang/algorithm/README.md
2020/10/week3/1ilsang/algorithm/leetcode1608.js
2020/10/week3/1ilsang/algorithm/leetcode1609.js
2020/10/week3/1ilsang/algorithm/leetcode1610.js
2020/10/week3/1ilsang/beta.md
2020/10/week3/1ilsang/english/README.md
2020/10/week3/1ilsang/english/naver-en.md
2020/10/week3/1ilsang/english/voca.md
2020/10/week4/1ilsang/README.md

1. 알고리즘: LeetCode Weekly Contest 209
2. 영어공부: 네이버영어, 말해보카
3. 혼자 공부하는 자바스크립트 베타리딩(chapter3)
1. 알고리즘: LeetCode Weekly Contest 210
2. 영어공부: 네이버영어, 말해보카
3. Next.js 공부 - 간단한 토이프젝

feat: complete

---

2020/10/week4/huisam/README.md
2020/11/week1/huisam/README.md

1. 기술 세미나 자료 정리
2. Interview 대비 Java 정리하기
3. HTTP 완벽가이드 20장 리다이렉션과 부하 균형 정리 
1. Line 면접
2. Kakao 면접
3. HTTP 완벽가이드 부록C 헤더 래퍼런스 정리

huisam: 10월 4주차 목표 완료

---

2020/10/week4/minhyungPark/README.md
2020/10/week4/minhyungPark/algorithm/Leetcode1624.kt
2020/10/week4/minhyungPark/algorithm/Leetcode1625.kt
2020/10/week4/minhyungPark/algorithm/Leetcode1626.kt

1. 알고리듬
2. ditto
3. ditto
1. 알고리듬
2. ditto
3. ditto

10월 4주차 완료

---

2020/10/week4/jjeda/README.md

1. 네트워크 원리 4장 읽기
2. 네트워크 원리 5장 읽기 
3. 네트워크 원리 6장 읽기
1. java로 알고리즘풀기
2. ditto 
3. ditto

feat: Complete 4th week of oct

---

2020/11/week1/huisam/README.md
2020/11/week2/huisam/README.md

1. Line 면접
2. Kakao 면접
3. HTTP 완벽가이드 부록C 정리
1. JVM & GC 블로그 포스팅
2. Reactive 스터디 준비
3. HTTP 완벽가이드 부록E 정리

huisam: 11월 2주차 목표 작성

---

2020/11/week1/juheekimm/README.md

1. 면접 준비 - Java
2. 면접 준비 - Spring
3. 면접 준비 - Database
1. Programmers 문제풀이 - SQL (KB, CJ, 현대 코딩테스트 대비)
2. Programmers/백준 문제풀이 - 코딩테스트 (KB, CJ, 현대 코딩테스트 대비)
3. 면접 준비
면접 준비하면서 일단 혼자 볼 용도로 적어놨더니.. 올릴 수 있게 정리하는데에 시간이 좀 걸리네요 ;ㅁ;
저거밖에 안 한건 아닌데 ㅜㅜ 정리되는대로 차차 올리겠습니다.
다들 한주동안 고생하셨습니다!

feat: Complete 1st week of Nov

---

2020/11/week1/minhyungPark/README.md
2020/11/week1/minhyungPark/algorithm/Leetcode1629.kt
2020/11/week1/minhyungPark/algorithm/Leetcode1630.kt
2020/11/week1/minhyungPark/algorithm/Leetcode1631.kt

1. 알고리즘
2. ditto
3. ditto
1. 알고리즘
2. ditto
3. ditto

11월 1주차 완료

---

2020/11/week3/InyoungJ/README.md

1. Githup 환경 이해하기 - 명령어 정리
2. Python Study - Python 명령어, 데이터 타입 이해하기
3. Mysql - DDL 수행 시 유의사항 버전 별 정리하기

feat: next week to do list

---

2020/11/week2/jjeda/CarGraph.kt
2020/11/week2/jjeda/MatchStick.java
2020/11/week2/jjeda/MatchStick.kt
2020/11/week2/jjeda/README.md

1. 우아한 테크코스 지원
2. 알고리즘
3. 알고리즘
1. 1% 네트워크 6장 정리
2. gRPC deep dive- 내용 미정
3. ditto

feat: Complete second week of nov

---

2020/11/week2/minhyungPark/README.md
2020/11/week2/minhyungPark/algorithm/LeetCode1640.kt
2020/11/week2/minhyungPark/algorithm/LeetCode1641.kt
2020/11/week2/minhyungPark/algorithm/LeetCode1642.kt

1. 알고리듬
2. ditto
3. ditto
1. 쿠버네티스 기초다지기 14장 정리
2. 알고리즘
3. ditto

11월 2주차 완료

---

2020/11/week2/sunivers/README.md

1. 알고리즘 문제풀기
2. 알고리즘 문제풀기
3. 알고리즘 문제풀기
1. 알고리즘 문제풀기
2. 알고리즘 문제풀기
3. 알고리즘 문제풀기

Complete 2nd week of Nov

---

2020/11/week2/nook1208/README.md
2020/11/week2/nook1208/english.md
2020/11/week2/nook1208/icache_dcache.md
2020/11/week2/nook1208/rust-os/0001-Tutorial-03-Hacky-Hello-World-is-done.patch
2020/11/week2/nook1208/rust-os/chap3_analysis.md
2020/11/week3/nook1208/README.md

1. rust-os: 03 hacky_hello_world 분석 및 구현
3. Instruction cache, Data cache 정리
1. rust-os: 04_zero_overhead_abstraction 분석 및 구현
3. Linux VA to PA translation 정리

feat: Nov 2nd plan completed

---

2020/11/week3/jjeda/README.md

1. 1% 네트워크 6장 정리 
2. gRPC 정리
3. Asynchronous&reactive 정리
1. 1% 네트워크 6장 발표준비
2. 네이버웹툰 지원
3. 네이버예약플랫폼 지원

feat: Complete week3

---

2020/11/week3/juheekimm/README.md
2020/11/week3/juheekimm/study/os_study_1st.md
2020/11/week3/juheekimm/study/programmers_sql.md

1. Programmers SQL 풀이 - 코딩테스트 대비
2. Programmers/백준 알고리즘 풀이 - 코딩테스트 대비
3. 면접 준비
당장 면접이 급해서 부득이하게 OS 공부 내용은 사진으로 올립니다 😭
바쁜거 끝나면 꼭 md파일로 정리해서 cs repo에 기여하겠습니다 😄 😄
1. Naver 최종 면접 준비 : 전공 기초
2. 현대자동차, SK 면접 준비 : Cloud, MSA
3. 현대IT&E, CJ 면접 준비 : Web Programming

feat(juheekimm): 11월 3주차 완료

---

2020/11/week3/sunivers/README.md

1. 파이썬 알고리즘 풀기 1
2. 파이썬 알고리즘 풀기 2
3. 파이썬 알고리즘 풀기 3
1. 파이썬 알고리즘 풀기 1
2. 파이썬 알고리즘 풀기 2
3. 자바스크립트 패턴과 테스트 책 2장 정리

✨ Complete 3rd week of Nov

---

2020/11/week4/jjeda/README.md

1. 1% 네트워크 6장 발표준비
2. 네이버 예약플랫폼 지원
3. 네이버 웹툰 지원 
실습과 그림으로 배우는 리눅스 구조
1. chapter 1,2,3 
2. chapter 4
3. chapter 5

feat: Complete 20201122

---

2020/11/week4/kerochuu/LCS.java
2020/11/week4/kerochuu/README.md
2020/11/week4/kerochuu/골목대장호석.java
2020/11/week4/kerochuu/문자열지옥.java

1. 백준 알고리즘 문제풀이(hashMap)
2. 백준 알고리즘 문제풀이(binarySearch + dijkstra)
3. 백준 알고리즘 문제풀이(dp)
1. 백준 알고리즘 문제풀이(자료구조)
2. 백준 알고리즘 문제풀이(자료구조)
3. 백준 알고리즘 문제풀이(그래프)

feat(kerochuu): Complete 4th week of Nov.

---

2020/11/week4/woohyeonjo/Kubernetes.md
2020/11/week4/woohyeonjo/README.md

1. 알고리즘 풀이를 위한 각종 편의 함수 구현 블로깅
2. 쿠버네티스 강의 듣기
- ~도커 컨테이너 실행 연습문제
3. 이사왔으니 집을 잘 꾸며보자
1. 5G NR 차세대 무선기술 책 읽기
- chapter 1, 2, 3, 4
2. 쿠버네티스 강의 듣기
- ~ 풀스택 워드프레스 컨테이너 이미지 만들기
3. Conbination, Permutation, Powerset 알고리즘 c++로 정리하기 (블로깅)

feat(woohyeonjo): Complete 4nd week of Nov

---

2020/11/week4/nook1208/README.md
2020/11/week4/nook1208/english.md
2020/11/week4/nook1208/rust-os/0001-Add-synchronization.rs-to-use-pseudo-lock.patch
2020/11/week4/nook1208/rust-os/README.md
2020/11/week4/nook1208/rust-os/chap5.md
2020/11/week4/nook1208/tlb.md
2020/11/week5/nook1208/README.md

Signed-off-by: Sunwook Eom <sunwook5492@gmail.com>
1. [rust-os: 05_safe_globals 분석 및 구현 #1](rust-os/README.md)
2. [영어공부: 미티영 Friends 쉐도잉 & 문장 암기](english.md)
3. [TLB 정리](tlb.md)
1. rust-os: 05_safe_globals 분석 #2
3. ARMv8 PSTATE 정리

feat(nook1208): Nov 4th plan completed

---

2020/11/week4/sunivers/README.md

1. [파이썬 알고리즘 풀기 1](https://github.com/sunivers/Study__Algorithm/commit/c71b40487686a1add1aef702cc21c8f9c9761255)
2. [파이썬 알고리즘 풀기 2](https://github.com/sunivers/Study__Algorithm/commit/05dac2c6a86da01bd1b81f2d2f28cadf554b87e6)
3. [자바스크립트 패턴과 테스트 책 2장 3분의 1 정리](https://github.com/sunivers/javascript-pattern-test/blob/master/1%EB%B6%80_%EA%B8%B0%EC%B4%88_%EB%8B%A4%EC%A7%80%EA%B8%B0/02_%EB%8F%84%EA%B5%AC_%EB%8B%A4%EB%A3%A8%EA%B8%B0.md) - 생각보다 양이 많아서 일부만 정리하였고 차주에 마저 정리하려고 합니당
1. 자바스크립트 패턴과 테스트 책 2장 마저 정리
2. 인터렉션 디자인 튜토리얼 따라해보기
3. 파이썬 알고리즘 풀기

✨ 11월 4주차 완료

---

2020/11/week5/hayoung/README.md

1. 
2. 
3. 
첫주라 이번주 목표만 써봤습니다. 
1. Leetcode Weekly 216 문제 풀이하기
2. pwa-react-exercies-dary(개인 공부 프로젝트)에 커밋 하나 남기기
3. webassembly-in-action 에 책 3장 공부하고 커밋 남기기

11월 5주차 목표 작성

---

2020/11/week5/jjeda/README.md

1. 리눅스 구조 1,2,3 장
2. 4장
3. 5장
1. 리눅스 구조 6장
2. 7장
3. 8장

feat: Complete 20201129

---

2020/11/week5/hayoung/README.md
2020/12/week1/hayoung/README.md

1. Leetcode 문제 풀이
2. 개인프로젝트에 커밋 한개 남기기
3. Web assembly in action  3장 공부하고 커밋 남기기
1. Leetcode 문제 풀이 - 손코딩
2. Rust 가 뭔지 알아보기
3. Next js 공부하기 - 공식 독스 기준

11월 5주차 목표 완료 및 12월 1주차 목표 작성

---

2020/11/week5/kerochuu/README.md
2020/11/week5/kerochuu/스트레이트스위치게임.java
2020/11/week5/kerochuu/좀비.java
2020/11/week5/kerochuu/진우의민트초코우유.java

1. 백준 알고리즘 문제풀이(구현)
2. 백준 알고리즘 문제풀이(call by value & reference)
3. 백준 알고리즘 문제풀이(bfs + dijkstra)
1. 백준 알고리즘 문제풀이
2. 백준 알고리즘 문제풀이
3. 백준 알고리즘 문제풀이

feat(kerochuu): Complete 5th week of Nov.

---

2020/11/week5/nook1208/ARMv8_PSTATE.md
2020/11/week5/nook1208/README.md
2020/11/week5/nook1208/english.md
2020/11/week5/nook1208/rust-os/chap5.md
2020/12/week1/nook1208/README.md

Signed-off-by: Sunwook Eom <sunwook5492@gmail.com>
1. rust-os: 05_safe_globals 분석 #2
3. ARMv8 PSTATE 정리
1. rust-os: 05_safe_globals 분석 #3
3. ARMv8 Exception handling 정리

feat(nook1208): Nov 5th plan completed

---

2020/11/week5/minhyungPark/README.md
2020/11/week5/minhyungPark/netty-in-action.md

1. 네티 인 액션 5장 읽기
2. 네티 인 액션 6장 읽기
3. 네티 인 액션 7장 읽기
1. 스프링 리액티브 1,2장 읽기
2. os가 보이는 그림책 읽기
3. 알고리즘 문제 풀이

11월 5주차 완료

---

2020/11/week5/sunivers/README.md

1. [자바스크립트 패턴과 테스트 책 2장 마저 정리](https://github.com/sunivers/javascript-pattern-test/blob/master/1%EB%B6%80_%EA%B8%B0%EC%B4%88_%EB%8B%A4%EC%A7%80%EA%B8%B0/02_%EB%8F%84%EA%B5%AC_%EB%8B%A4%EB%A3%A8%EA%B8%B0.md)
2. [인터렉션 디자인 튜토리얼 따라해보기](https://github.com/sunivers/interactive_coding_tutorial/tree/master/moving_wave)
3. [파이썬 알고리즘 풀기](https://github.com/sunivers/Study__Algorithm/commit/44a60c87225970ad6946e52fe18c1810c41a3b2e)
1. 자바스크립트 패턴과 테스트 책 3장 정리
2. 파이썬 알고리즘 풀기
3. 토이 프로젝트 진행
이번주 목표 완료가 좀 늦었습니다 ㅠ_ㅠ 다음주는 부지런히 해서 제때 올려보겠습니당!

✨ 11월 5주차 완료

---

2020/12/week1/nook1208/ARMv8_Exception_handling.md
2020/12/week1/nook1208/README.md
2020/12/week1/nook1208/english.md
2020/12/week1/nook1208/rust-rasp-os/0001-Chap-05-Safe-Globals-is-done.patch
2020/12/week1/nook1208/rust-rasp-os/README.md
2020/12/week1/nook1208/rust-rasp-os/chap5.md
2020/12/week2/nook1208/README.md

Signed-off-by: Sunwook Eom <sunwook5492@gmail.com>
1. rust-os: 05_safe_globals 분석 - 3
3. ARMv8 Exception handling 정리
1. rust-os: chap 6 drivers_gpio_uart 분석 - 1
3. rust: Lifetime 정리

feat(nook1208) Dec 1st plan completed

---

2020/12/week1/jjeda/README.md

1. 리눅스 구조 6장
2. 리눅스 구조 7장
3. 리눅스 구조 8장
1. HTTP 정리
2. 네트워크 정리
3. 데이터베이스 개론 1장

feat: Complete 201206

---

2020/12/week1/kerochuu/Double_SAT_3.java
2020/12/week1/kerochuu/README.md
2020/12/week1/kerochuu/대기업승범이네.java
2020/12/week1/kerochuu/준오는최종인재야.java

1. 백준 알고리즘 문제풀이(SCC)
2. 백준 알고리즘 문제풀이(treeDP)
3. 백준 알고리즘 문제풀이(treeDP)
1. 백준 알고리즘 문제풀이(SCC)
2. 백준 알고리즘 문제풀이(구현)
3. 백준 알고리즘 문제풀이(그래프)

feat(kerochuu): Complete 1st week of Dec.

---

2020/12/week1/sunivers/README.md

1. [자바스크립트 패턴과 테스트 책 3장 정리](https://github.com/sunivers/javascript-pattern-test/blob/master/1%EB%B6%80_%EA%B8%B0%EC%B4%88_%EB%8B%A4%EC%A7%80%EA%B8%B0/03_%EA%B0%9D%EC%B2%B4%EB%A5%BC_%EB%B0%94%EB%A5%B4%EA%B2%8C_%EB%A7%8C%EB%93%A4%EA%B8%B0.md)
2. [파이썬 알고리즘 풀기](https://github.com/sunivers/Study__Algorithm/commit/98a4bc9e63e34b316a5b9df1bdbf726243823f81)
3. [토이 프로젝트 진행](https://user-images.githubusercontent.com/26291081/101282167-c5914500-3816-11eb-85f9-fb101512f891.png)
1. 자바스크립트 패턴과 테스트 책 4장 정리
2. 파이썬 알고리즘 풀기
3. 토이 프로젝트 진행

✨ 12월 1주차 완료

---

2020/12/week1/hayoung/README.md
2020/12/week2/hayoung/README.md

1. Leetcode Weekly 217 세가지를 풀었습니다. 217이 개인적으로 어려워서 겨우 겨우 보고, 오늘 면접이 있어서 저번주에는 프로그래머스 문제들 많이 풀었습니다. 
2. Rust가 뭔지 알아보기. 알아만 봤습니다.. 
3. Next js 공부하기 - 공식 독스보기도하고, 아직 프론트 지식이 부족해서, 다른 튜토리얼도 해봤습니다. 
1. Leetcode Weekly 218 풀기
2. Next js 공부하기 - 공식 독스에서 API Routes부분
3. Rust 공부

12월 1주차 목표 완료 / 12월 2주차 목표 작성

---

2020/12/week2/jjeda/README.md

1. HTTP 정리
2. 네트워크 정리
3. 데이터베이스 개론 1장
1. RDB vs NoSQL 정리
2. 인덱스 경험정리, 공부
3. 트랜잭션 경험정리 공부

feat: Complete 201213

---

2020/12/week2/nook1208/README.md
2020/12/week2/nook1208/english.md
2020/12/week3/nook1208/README.md

1. rust-os: chap 6 drivers_gpio_uart 분석 - 1
3. rust: Lifetime 정리
1. Rust-os: Chap 6 drivers_gpio_uart analysis - 2
2. Leetcode: Write a small rust program to solve a problem
3. English study: Friends shadowing & Memorize sentences

feat(nook1208) Dec 2nd plan completed

---

2020/12/week2/sunivers/README.md

1. [자바스크립트 패턴과 테스트 책 4장 정리](https://github.com/sunivers/javascript-pattern-test/blob/master/2%EB%B6%80_%ED%8C%A8%ED%84%B4%EC%9D%84_%EC%9D%91%EC%9A%A9%ED%95%9C_%EC%BD%94%EB%93%9C_%ED%85%8C%EC%8A%A4%ED%8C%85/01_%ED%8C%A8%ED%84%B4%EC%9D%B4_%EC%A2%8B%EC%9D%80_%EC%A0%90.md)
2. [파이썬 알고리즘 풀기](https://github.com/sunivers/Study__Algorithm/commit/f59cfa5e1e6b08e04a533403a95ef5aba08905cb)
3. [토이 프로젝트 진행](https://user-images.githubusercontent.com/26291081/102011156-d812fd80-3d85-11eb-91a2-49d64c2da592.png)
1. 자바스크립트 패턴과 테스트 책 5장 정리
2. 파이썬 알고리즘 풀기
3. 토이 프로젝트 진행

✨ 12월 2주차 완료

---

2020/12/week2/woohyeonjo/README.md
2020/12/week2/woohyeonjo/src/스트리밍서버.cpp

1. 신입 SW 교육 복습
2. Pro 시험 1문제
- 스트리밍서버
3. 5G NR 차세대 무선기술 책 읽기
1. Pro 대비 문제 1
2. Pro 대비 문제 1
3. 5G NR 차세대 무선기술 책 읽기
- CHAPTER07

feat(woohyeonjo): Complete 2nd week of Dec

---

2020/12/week2/kerochuu/README.md
2020/12/week2/kerochuu/내리막길.java
2020/12/week2/kerochuu/소수경로.java
2020/12/week2/kerochuu/스타트링크.java

1. 백준 알고리즘 문제풀이(treeDP)
2. 백준 알고리즘 문제풀이(bfs)
3. 백준 알고리즘 문제풀이(bfs)
1. 백준 알고리즘 문제풀이(그래프)
2. 백준 알고리즘 문제풀이(구현)
3. 백준 알고리즘 문제풀이(그래프)

feat(kerochuu): Complete 2nd week of Dec.

---

2020/12/week2/minhyungPark/README.md
2020/12/week2/minhyungPark/algorithm/LeetCode1672.kt
2020/12/week2/minhyungPark/algorithm/LeetCode1673.kt
2020/12/week2/minhyungPark/algorithm/LeetCode1674.kt

1. 알고리즘
2. ditto
3. ditto
1. CAP Theory 정리
2. 블로그 개편
3. 알고리듬

12월 2주차 완료

---

2020/12/week2/hayoung/README.md
2020/12/week3/hayoung/README.md

1. Leetcode Weekly 218 풀기
2. Next js 공부하기 
3. Rust 공부
1. Leetcode Weekly 219 풀기
2. https://github.com/reck1ess/next-realworld-example-app 따라하면서 next js 공부하기
3. Rust 공부 책 chapter1, chapter2

12월 2주차 완료 / 12월 3주차 목표 작성

---

2020/12/week2/jh20s/README.md
2020/12/week2/jh20s/leetcode #216/1662.cpp
2020/12/week2/jh20s/leetcode #216/1663.cpp
2020/12/week2/jh20s/leetcode #216/1664.cpp

1. [o] leet code contest #216
2. [o] [손에 잡히는 정규 표현식 1,2장 정리](https://blog.naver.com/PostList.nhn?blogId=jh20s&from=postList&categoryNo=19) 
3. [o] [손에 잡히는 정규 표현식 3,4장 정리](https://blog.naver.com/PostList.nhn?blogId=jh20s&from=postList&categoryNo=19)
1. 손에 잡히는 정규 표현식 5,6장 정리
2. 손에 잡히는 정규 표현식 7,8장 정리
3. 손에 잡히는 정규 표현식 9,10장 정리

feat: complete 2th Dec

---

2020/12/week3/nook1208/README.md
2020/12/week3/nook1208/english.md
2020/12/week4/nook1208/README.md

1. Rust-os: Chap 6 drivers_gpio_uart analysis - 2
2. Leetcode: Write a small rust program to solve a problem
3. English study: Friends shadowing & Memorize sentences
1. Rust-os: Chap 6 drivers_gpio_uart analysis - 3
2. Leetcode: Write a small rust program to solve a problem
3. English study: Friends shadowing & Memorize sentences

feat(nook1208): Dec 3rd plan completed

---

2020/12/week3/woohyeonjo/README.md
2020/12/week3/woohyeonjo/src/blockchain.cpp
2020/12/week3/woohyeonjo/src/두번이상등장하는문자열.cpp

1. Pro 대비 문제 1
- Block Chain
2. Pro 대비 문제 1
- 두 번 이상 등장하는 문자열
3. 5G NR 차세대 무선기술 책 읽기
- CHAPTER07
1.  Pro 대비 기출 문제
2. Pro 대비 기출 문제
3. Pro 대비 기출 문제

feat(woohyeonjo): Complete 3nd week of Dec

---

2020/12/week3/kerochuu/README.md
2020/12/week3/kerochuu/개미굴.java
2020/12/week3/kerochuu/교수님그림이.java
2020/12/week3/kerochuu/등산마니아2.java
2020/12/week3/kerochuu/마피아.java

1. 백준 알고리즘 문제풀이(treeDP)
2. 백준 알고리즘 문제풀이(dfs)
3. 백준 알고리즘 문제풀이(dfs)
1. 백준 알고리즘 문제풀이(treeDP)
2. 백준 알고리즘 문제풀이(그래프)
3. 백준 알고리즘 문제풀이(구현)

feat(kerochuu): Complete 3rd week of Dec.

---

2020/12/week3/jjeda/README.md

1. RDB vs NoSQL
2. DB index 정리
3. DB transaction 정리
1. 데이터베이스 개론 2장
2. 데이터베이스 개론 3장 
3. 데이터베이스 개론 4장

feat: Complete 201220

---

2020/12/week3/hayoung/README.md
2020/12/week4/hayoung/README.md

1. Leetcode Weekly 219 풀기(3번째 문제가 너무 어려웠습니다..)
2. Real World Next App 코드를 보면서 제대로된 프로젝트의 구조를 살펴봤습니다. 
3. Rust docs 챕터 1, 2를 공부했습니다. 
1. Leetcode에서 다이나믹 프로그래밍 문제를 3문제 풀기
2. Real World Next App 더 분석해보기
3. 코어자바스크립트 3, 4 장 정리하기

12월 3주차 완료 / 12월 4주차 목표 작성

---

2020/12/week3/minhyungPark/README.md
2020/12/week3/minhyungPark/algorithm/LeetCode1678.kt
2020/12/week3/minhyungPark/algorithm/LeetCode1679.kt

1. CAP 이론 정리
2. 블로그 개편
3. 알고리즘
1. 알고리즘
2. ditto
3. ditto

12월 3주차 완료

---

2020/12/week3/sunivers/README.md

1. [자바스크립트 패턴과 테스트 책 5장 정리](https://github.com/sunivers/javascript-pattern-test/blob/master/2%EB%B6%80_%ED%8C%A8%ED%84%B4%EC%9D%84_%EC%9D%91%EC%9A%A9%ED%95%9C_%EC%BD%94%EB%93%9C_%ED%85%8C%EC%8A%A4%ED%8C%85/05_%EC%BD%9C%EB%B0%B1_%ED%8C%A8%ED%84%B4.md)
2. [파이썬 알고리즘 풀기](https://github.com/sunivers/Study__Algorithm/commit/b0e0e25007ca96ec66d7af6e5f883030baf07e6c)
3. [토이 프로젝트 진행](https://user-images.githubusercontent.com/26291081/102717573-973b5b80-4326-11eb-98f3-adf08d8c44e9.png)
1. 자바스크립트 패턴과 테스트 책 6장 정리
2. 파이썬 알고리즘 풀기
3. 토이 프로젝트 진행

✨ 12월 3주차 목표 완료

---

2020/12/week4/woohyeonjo/README.md
2020/12/week4/woohyeonjo/src/gmemo.cpp
2020/12/week4/woohyeonjo/src/heapTest.cpp
2020/12/week4/woohyeonjo/src/sortedlist.cpp

1. Pro 대비 문제
- [GMemo](src/gmemo.cpp)
2. Pro 대비 문제
- [Heap 성능테스트](src/heapTest.cpp)
3. Pro 대비 문제
- [SortedList](src/sortedlist.cpp)
2020년 한 해 모두 수고많으셨습니다. 2021년도 더 활활타오르는 땔감이 되는 해가 됩시다.

feat(woohyeonjo): Complete 4nd week of Dec

---

2020/12/week4/jjeda/README.md

1.  데이터베이스 개론 2장 읽기
2. 데이터베이스 개론 3장 읽기
3. 데이터베이스 개론 4장 읽기
1. 데이터베이스 개론 5장 읽기
2. 데이터베이스 개론 6장 읽기
3. 데이터베이스 개론 7장 읽기

feat: Complete last week of 2020

---

2020/12/week4/hayoung/README.md

1. [Leetcode DP 3문제 풀기](https://github.com/I-am-interested-in-Javascript/My-LeetCode-Weekly-Contest/tree/master/Week%2011(DP))
2. Next js 공부하기: Real World Next App 분석 더하기 - [3일차](https://github.com/hayoung0Lee/Real-world-next-app#3%EC%9D%BC%EC%B0%A8-%ED%95%99%EC%8A%B5)
3. 코어자바스크립트 [3장](https://github.com/hayoung0Lee/we-hate-js/blob/hayoung/js/JavaScript/this.md), [4장](https://github.com/hayoung0Lee/we-hate-js/blob/hayoung/js/JavaScript/callback.md) 정리하기
1. 
2. 
3.

12월 4주차 목표 완료

---

2020/12/week4/kerochuu/README.md
2020/12/week4/kerochuu/같이눈사람만들래.java
2020/12/week4/kerochuu/비밀번호제작.java
2020/12/week4/kerochuu/사장님달려가고있습니다.java

1. 백준 알고리즘 문제풀이(two pointer)
2. 백준 알고리즘 문제풀이(bfs & bit연산)
3. 백준 알고리즘 문제풀이(bfs & 구현)
1. 백준 알고리즘 문제풀이(bit연산)
2. 백준 알고리즘 문제풀이(구현)
3. 블로그 연말후기 작성

feat(kerochuu): Complete 4th week of Dec.

---

2020/12/week4/minhyungPark/README.md
2020/12/week4/minhyungPark/algorithm/LeetCode1688.kt
2020/12/week4/minhyungPark/algorithm/LeetCode1689.kt
2020/12/week4/minhyungPark/algorithm/LeetCode1690.kt

1. 알고리즘
2. ditto
3. ditto
다들 내년에도 화이팅 👍

feat: complete 4th of Dec

---

2020/12/week4/nook1208/README.md

1. [Rust-os: Chap 6 drivers_gpio_uart analysis - 3](https://github.com/nook1208/rust-rasp-os/commits/master)
2. [Leetcode: Write a small rust program to solve a problem](https://github.com/nook1208/leet_code/commit/c1b7008698ac80f157033bcf337ef1b8152da1be)
3. [English study: Friends shadowing & Memorize sentences](https://github.com/nook1208/english/commits/main)
2020 올 한해 고생 많으셨습니다 ~

feat(nook1208): Dec 4th plan completed

---

2020/12/week4/1ilsang/README.md
2020/12/week4/1ilsang/algorithm/README.md
2020/12/week4/1ilsang/algorithm/leetcode1688.js
2020/12/week4/1ilsang/algorithm/leetcode1689.js
2020/12/week4/1ilsang/english/naver-en.md
2020/12/week4/1ilsang/english/voca.md

1. 알고리즘: LeetCode Weekly Contest 219 도전
2. 영어공부: 네이버영어, 말해보카 도전
3. [2020 회고 작성하기](https://github.com/Road-of-CODEr/stupid-week/issues/204): 정적 배포를 할지 고민중
올해의 마지막 PR 이네요. 새로운 레포에서 다시 열심히~

feat: TODO

---

2020/12/week4/jh20s/README.md
2020/12/week4/jh20s/leetcode #220/1694.cpp
2020/12/week4/jh20s/leetcode #220/1695.cpp
2020/12/week4/jh20s/leetcode #220/1696.cpp
2020/12/week4/jh20s/leetcode #220/1697.cpp

1. [o] [leetcode contest#220 1번](https://github.com/jh20s/stupid-week/tree/jh20s/2020/12/week4/jh20s/leetcode%20%23220)
2. [o] [leetcode contest#220 2번](https://github.com/jh20s/stupid-week/tree/jh20s/2020/12/week4/jh20s/leetcode%20%23220)
3. [o] [leetcode contest#220 3,4번](https://github.com/jh20s/stupid-week/tree/jh20s/2020/12/week4/jh20s/leetcode%20%23220)

feat:complete 4th dec

---

2020/12/week4/parkinhyo/README.md

1. 파이썬 알고리즘 인터뷰 11장 해시 테이블
2. 파이썬 알고리즘 인터뷰 12장 그래프
3. 오픽 2주만에 끝내는 해커스 오픽 start 설문조사에 체크할 주제 전부 수강

feat(parkinhyo): Complete 4th week of Dec.
